### ISSUE TITLE
sonic_pi stop command doesn't work on os x (10.10.2)

### ISSUE THREAD

**Issue by simons-design** [Widdershin/sonic-pi-cli#1]
thanks for this nice little package. only the `sonic_pi stop` command doesn't work on os x (10.10.2). it doesn't give errors either.

**Comment by Widdershin** [comment]
Hey mate,

sonic-pi-cli was developed on OS X, and I've had no luck reproducing this issue.

Can you confirm that Sonic Pi is running, and music is playing when you issue this command?

I've tested it by running the following:
```
sonic_pi sample :loop_amen_full
sonic_pi stop
```

Also, when the command is run, you should see a message in the Sonic Pi log window, "Stopping all runs...". Is that present?

**Comment by rbnpi** [comment]
It works fine on my iMac running 10.10.2

**Comment by simons-design** [comment]
Sonic Pi is running, and music is playing when i run this command:

    $ sonic_pi sample :loop_amen_full

this does nothing and doesn’t say anything in the Sonic Pi log window:

    $ sonic_pi stop

However, I did spot this error:

    Error: wrong number of arguments (0 for 1)
    /opt/homebrew-cask/Caskroom/sonic-pi/latest/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/mods/sound.rb:2192:in `stop'
    eval:1:in `block in __spider_eval'
    /opt/homebrew-cask/Caskroom/sonic-pi/latest/Soni Pi.app/app/server/sonicpi/lib/sonicpi/spider.rb:426:in `eval'
    /opt/homebrew-cask/Caskroom/sonic-pi/latest/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/spider.rb:426:in `block in __spider_eval'

Also when I installed `sonic-pi-cli` I also had to install `osc-ruby`.

Hope this helps.

**Comment by Widdershin** [comment]
Try `gem install sonic-pi-cli` again, I suspect this might be fixed in
v0.0.2.

**Comment by simons-design** [comment]
yes, that fixes it. i had v0.0.1. thanks.
