### ISSUE TITLE
Viewing of error and status messags

### ISSUE THREAD

**Issue by lpil** [Widdershin/sonic-pi-cli#10]
Hey!

It is possible to view the error message when invalid code is sent to Sonic Pi?

Cheers,
Louis

**Comment by Widdershin** [comment]
Not sure! I had a look tonight.

Seems like the current communication from the backend to the GUI is done over TCP/UDP.

https://github.com/samaaron/sonic-pi/blob/master/app/server/bin/sonic-pi-server.rb#L327-L332

I tried to spin up an OSC server to listen on 4558 but that's already taken by the Sonic Pi gui. (That's actually how we check if Sonic Pi is running).

It looks like @samaaron is working on a new server that uses websockets and supports multiple clients (https://github.com/samaaron/sonic-pi/blob/v2.9.0/app/server/bin/ws.rb). Not too sure what the plans are for that, but it seems once that's done this would be possible.

**Comment by lpil** [comment]
FYI I wrote a tool for viewing logs here -> https://github.com/lpil/sonic-pi-tools

**Comment by Widdershin** [comment]
Awesome! I like the idea of using a compiled tool to avoid interpreter startup time. I'll add a link to `sonic-pi-tools` to the README.

**Comment by lpil** [comment]
That was my motivation- removing the tiny delay of Ruby starting made everything feel a lot slicker. :)

**Comment by lpil** [comment]
Also thanks for this, I pretty much copied your work line for line!

**Comment by lpil** [comment]
Gunna close this as there is another tool for this.
