### ISSUE TITLE
The stop command no longer works

### ISSUE THREAD

**Issue by Widdershin** [Widdershin/sonic-pi-cli#7]
Tried out `sonic_pi stop` today, no longer works. Something has probably changed in the structure of the OSC commands on Sonic Pi's end.

**Comment by neumanrq** [comment]
I'm using your SonicPi CLI together with [sonic-pi.vim](https://github.com/dermusikman/sonicpi.vim/blob/master/plugin/sonicpi.vim) within OSX 10.10.4 - and for me the stop command still works perfect!

**Comment by Widdershin** [comment]
Working great for me in the latest release ¯\_(ツ)_/¯
