### ISSUE TITLE
New changes in Sonic Pi will break this gem

### ISSUE THREAD

**Issue by rbnpi** [Widdershin/sonic-pi-cli#8]
Sam Aaron has just made a change in sp 2.7dev which stops the cli from working. See 
https://github.com/samaaron/sonic-pi/commit/74bc44edb5d827315d799963c3109d1906a19c65

Of course it is still fine now, and will still work until 2.7 is released, but thought you should know.

**Comment by Widdershin** [comment]
Thanks for the heads up :smile: 

From reading that commit, it just looks like I'll have to send a GUI ID as my first argument on all my OSC calls.

I'll try and get to this before 2.7 is released but a pull request is welcome if anyone wants to take a crack at it.

**Comment by rbnpi** [comment]
Version 2.7 is now out.
Looking at the changes there are I think two involved that need addresssing.
These are covered in 
https://github.com/samaaron/sonic-pi/commit/74bc44edb5d827315d799963c3109d1906a19c65
and possibly
https://github.com/samaaron/sonic-pi/commit/607cb0d101aea6106fa86f4b2af96aeebdd48712

i have stuck a note on the article I wrote using the cli, warning readers and saying stick to version 2.6 for now if you want to use the CLI.

Robin

**Comment by Widdershin** [comment]
Hey Robin,

Thanks for the heads up re: the 2.7 release.

I'll try and get a fix out ASAP. I just tried out @xavriley's fix and it doesn't look like it's working.

I should have some time tonight to do some investigation but if anyone has any insight into what needs to be done I would love to hear it (*cough* @samaaron :smile:).

**Comment by Widdershin** [comment]
@xavriley's fix actually worked great, I additionally hardcoded the GUI_ID as `SONIC_PI_CLI` for now.

I have released v0.0.4, let me know if you run into any issues.

**Comment by rbnpi** [comment]
Thanks for sorting this out. Works fine now
